---
title: "First Knit"
author: "Rabi Elkhoury"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended high school at William J. Pete Knight High School, in Palmdale, CA.  I graduated just a year ago, with honors, and as a member of the California Scholarship Federation.  I find topics in English class to come easier, but I have enjoyed Math classes far more as a student.  As a math student, I have studied Statistics and Calculus in great depth, and find them to be enjoyable topics.  I did the best in AP Calculus AB.  My group and I had the highest scores of any group in our class, and we all finished with an "A".

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a computer that runs on the Windows operating system, and is powered by AMD and HP parts.  I would rate myself about a 7 on the computer knowledge scale, as I previously wanted to be a software engineer.  My internet access is quite good at home, and I tend not to have any connection issues.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called by my normal name, "Rabi".  Some people tend to call me "Robs", and I don't mind that, either.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I would like to work in the bio medical field for a career.  This has been an aspiration of mine for as long as I can remember.  Biology and chemistry are the subjects in college that I tend towards most.  Currently,  I am working towards an Associate's Degree in Biology, which I hope to further into a Bachelor's Degree at a four-year institution.  Later, I would like to enter either Graduate or Medical school, in order to further my career goals.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




